In [1]:
import numpy as np
from sklearn.decomposition import PCA

# Define a 2x2 matrix
X = np.array([
    [2, 4],
    [6, 8]
])

print("Original Matrix:\n", X)

# Apply PCA
pca = PCA(n_components=2)

# Fit and transform
X_pca = pca.fit_transform(X)

print("\nPCA Transformed Data:\n", X_pca)
print("\nPrincipal Components:\n", pca.components_)
print("\nExplained Variance:\n", pca.explained_variance_)

Original Matrix:
 [[2 4]
 [6 8]]

PCA Transformed Data:
 [[-2.82842712  0.        ]
 [ 2.82842712  0.        ]]

Principal Components:
 [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]

Explained Variance:
 [16.  0.]


In [2]:
import numpy as np

# Define the same 2x2 matrix
X = np.array([
    [2, 4],
    [6, 8]
])

print("Original Matrix:\n", X)

# Apply SVD
U, S, Vt = np.linalg.svd(X)

print("\nU Matrix:\n", U)
print("\nSingular Values:\n", S)
print("\nV Transpose Matrix:\n", Vt)

Original Matrix:
 [[2 4]
 [6 8]]

U Matrix:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]

Singular Values:
 [10.92997141  0.73193238]

V Transpose Matrix:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]
